# Generated by Django 4.2 on 2026-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_servicepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/backgrounds/'),
        ),
    ]
