# Generated by Django 4.2 on 2026-03-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clothing_clothingcategory_clothingimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.clothingcategory'),
        ),
        migrations.AlterField(
            model_name='clothingcategory',
            name='slug',
            field=models.SlugField(),
        ),
    ]
